name: 'Haskell environment'
description: 'Setup a Haskell environment with Haskell-stack and cabal'
inputs: []
outputs: []
runs:
  using: "composite"
  steps:
    - name: add ppa
      run: sudo add-apt-repository -y ppa:hvr/ghc
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get install cabal-install-3.0 haskell-stack
