name: 'Deploy to hackage'
description: 'Upload the tarball to hackage'
inputs:
  HACKAGE_USERNAME:
    description: 'The hackage username to use to upload the package'
    required: true
  HACKAGE_PASSWORD:
    description: 'The hackage password to use to upload the package'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create documentation
      run: "stack haddock"
      shell: bash
    - name: Construct a hackage tarball
      run: "stack sdist"
      shell: bash
    - name: Determine the sdist path
      run: echo "::set-output name=sdist-path::$(stack path --dist-dir)"
      shell: bash
      id: sdist-path
    - name: upload the tarball
      run: "stack upload"
      shell: bash
      env:
        HACKAGE_USERNAME: "${{ inputs.HACKAGE_USERNAME }}"
        HACKAGE_PASSWORD: "${{ inputs.HACKAGE_PASSWORD }}"
