name: 'Deploy to hackage'
description: 'Upload the tarball to hackage'
inputs:
  HACKAGE_USERNAME:
    description: 'The hackage username to use to upload the package'
    required: true
  HACKAGE_PASSWORD:
    description: 'The hackage password to use to upload the package'
    required: true
  resolver:
    description: 'Which resolver is used to compile the package'
    required: true
    default: lts-21.1
runs:
  using: "composite"
  steps:
    - name: Create documentation
      run: "stack --resolver '${{ inputs.resolver }}' haddock"
      shell: bash
    - name: Construct a hackage tarball
      run: "stack --resolver '${{ inputs.resolver }}' sdist"
      shell: bash
    - name: Determine the sdist path
      run: echo "::set-output name=sdist-path::$(stack --resolver '${{ inputs.resolver }}' path --dist-dir)"
      shell: bash
      id: sdist-path
    - name: upload the tarball
      run: "echo 'n' | stack --resolver '${{ inputs.resolver }}' upload ."
      shell: bash
      env:
        HACKAGE_USERNAME: "${{ inputs.HACKAGE_USERNAME }}"
        HACKAGE_PASSWORD: "${{ inputs.HACKAGE_PASSWORD }}"
