name: 'build Haskell project'
description: 'Build the project with Haskell-stack'
inputs:
  ghcoptions:
    description: Options passed to the GHC compiler
    required: true
    default: -Wall -Werror
  resolver:
    description: Which resolver is used to compile the package
    required: true
    default: lts-19.12
runs:
  using: "composite"
  steps:
    - name: build the Haskell software
      run: "stack build --resolver '${{ inputs.resolver }}' --ghc-options='${{ inputs.ghcoptions }}'"
      shell: bash
