name: 'Add CNAME to directory'
description: 'Add a CNAME file to a directory, typically for GitHub pages'
inputs:
  folder:
    description: The directory where to add the item.
    required: true
    default: "."
  cname:
    description: The value for the CNAME file.
    required: true
  cnamefile:
    description: The name of the CNAME file.
    required: true
    default: CNAME
runs:
  using: "composite"
  steps:
    - name: Create the CNAME file
      run: "touch \"${{ inputs.folders }}/${{ inputs.cnamefile }}\""
      shell: bash
    - name: Create a CNAME file
      run: "echo \"${{ inputs.cname }}\" > \"${{ inputs.folder }}/${{ inputs.cnamefile }}\""
      shell: bash
