name: 'Validate yaml files'
description: 'Check if the yaml files are valid'
inputs:
  globpattern:
    description: The glob pattern that specifies what file to validate
    required: true
    default: "*.yaml *.yml"
runs:
  using: "composite"
  steps:
    - name: install the yamllint package
      run: "pip3 install --user yamllint"
      shell: bash
    - name: Run yaml lint
      run: "yamllint -d relaxed ${{ inputs.globpattern }}"
      shell: bash
