name: 'Haskell environment'
description: 'Setup a Haskell environment with Haskell-stack and cabal'
runs:
  using: "composite"
  steps:
    # - name: add ppa
    #   run: sudo add-apt-repository -y ppa:hvr/ghc
    #   shell: bash
    - name: update package database
      run: sudo apt-get update
      shell: bash
    - name: install required packages
      run: sudo apt-get install cabal-install haskell-stack
      shell: bash
    - name: upgrade stack
      run: stack upgrade
      shell: bash
