name: 'Run Haskell benchmarks'
description: 'Run the Haskell benchmarks with a specific resolver'
inputs:
  resolver:
    description: The resolver used to run the tests
    required: true
    default: lts-17
  output-file:
    description: The name of the HTML file that will show the output of the benchmarks.
    required: true
    default: benchmarks.html
runs:
  using: "composite"
  steps:
    - name: Run the test
      run: "stack --no-terminal --skip-ghc-check bench --benchmark-arguments \"--output=${{ inputs.output-file }}\" --resolver \"${{ inputs.resolver }}\""
      shell: bash
