name: Valid yaml
on: push

jobs:
  linux1:
    name: Validate yml of actions
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: validate actions
      uses: hapytex/github-actions/actions/validate-yaml@master
      with:
        globpattern: "actions/*/*.yml"
